[package]
name = "nanoreap"
version = "0.1.0"
entrypoint = "index.typ"
authors = ["bjoluc <mail@bjoluc.de>"]
description = "Templates"
repository = "https://github.com/kocheariadne/templates-typst-nanoreap"
categories = ["report"]
disciplines = ["computer-science"]
compiler = "0.13.1"

[template]
path = "template"
entrypoint = "seminar-report.typ"
thumbnail = "thumbnail.png"
